### Obtener todos los productos
GET http://localhost:3000/productos

### Obtener un producto por ID
GET http://localhost:3000/productos/1

###
POST http://localhost:3000/productos
Content-Type: application/json

{
  "nombre": "Martillo",
  "precio": 150,
  "descripcion": "Martillo de acero para carpinteria",
  "disponible": true
}
###
PUT http://localhost:3000/productos/1
Content-Type: application/json

{
  "precio": 200
}

###
DELETE http://localhost:3000/productos/1

